# -*- restclient -*-
#
# Get all notes
GET http://localhost:3000/users/notes

# Get all notes of user with userID 1
GET http://localhost:3000/users/1/notes

# Get all notes of user with userID 1
GET http://localhost:3000/users/2/notes

# Get note userID 1 noteID 1
GET http://localhost:3000/users/1/notes/1

# Add note for userID 1
POST http://localhost:3000/users/1/notes
Content-type: application/json
{
    "note": "Test note"
}

# Add note for userID 1
POST http://localhost:3000/users/1/notes
Content-type: application/json
{
    "note": "Test note 2"
}

# Add note for userID 2
POST http://localhost:3000/users/2/notes
Content-type: application/json
{
    "note": "Test note user 2"
}
